# Generated by Django 4.2.7 on 2024-07-13 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('kernel', '0001_initial'),
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zhuankepinggujilu',
            name='ke_hu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kernel.operator', verbose_name='客户'),
        ),
        migrations.AddField(
            model_name='zhuankepinggujilu',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_pid', to='kernel.process', verbose_name='作业进程'),
        ),
        migrations.AddField(
            model_name='zhengzhuang',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_attributes', to='contenttypes.contenttype', verbose_name='隶属主体'),
        ),
        migrations.AddField(
            model_name='zhengzhuang',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_pid', to='kernel.process', verbose_name='作业进程'),
        ),
        migrations.AddField(
            model_name='zhenduanjichuliyijianjilu',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_attributes', to='contenttypes.contenttype', verbose_name='隶属主体'),
        ),
        migrations.AddField(
            model_name='zhenduanjichuliyijianjilu',
            name='jian_yi_fang_an',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kernel.service', verbose_name='建议方案'),
        ),
        migrations.AddField(
            model_name='zhenduanjichuliyijianjilu',
            name='ke_hu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kernel.operator', verbose_name='客户'),
        ),
        migrations.AddField(
            model_name='zhenduanjichuliyijianjilu',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_pid', to='kernel.process', verbose_name='作业进程'),
        ),
        migrations.AddField(
            model_name='zhenduanjichuliyijianjilu',
            name='zhen_duan',
            field=models.ManyToManyField(blank=True, related_name='zhen_duan', to='applications.zhenduan', verbose_name='诊断'),
        ),
        migrations.AddField(
            model_name='zhenduanjichuliyijianjilu',
            name='zheng_zhuang',
            field=models.ManyToManyField(blank=True, related_name='zheng_zhuang', to='applications.zhengzhuang', verbose_name='症状'),
        ),
        migrations.AddField(
            model_name='zhenduan',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_attributes', to='contenttypes.contenttype', verbose_name='隶属主体'),
        ),
        migrations.AddField(
            model_name='zhenduan',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_pid', to='kernel.process', verbose_name='作业进程'),
        ),
        migrations.AddField(
            model_name='yuyuejilu',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_attributes', to='contenttypes.contenttype', verbose_name='隶属主体'),
        ),
        migrations.AddField(
            model_name='yuyuejilu',
            name='fu_wu_xiang_mu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kernel.service', verbose_name='服务项目'),
        ),
        migrations.AddField(
            model_name='yuyuejilu',
            name='ke_hu_lai_yuan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='applications.kehulaiyuan', verbose_name='客户来源'),
        ),
        migrations.AddField(
            model_name='yuyuejilu',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_pid', to='kernel.process', verbose_name='作业进程'),
        ),
        migrations.AddField(
            model_name='yuyuejilu',
            name='yu_yue_yi_sheng',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kernel.operator', verbose_name='预约医生'),
        ),
        migrations.AddField(
            model_name='xiaofeijilu',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_attributes', to='contenttypes.contenttype', verbose_name='隶属主体'),
        ),
        migrations.AddField(
            model_name='xiaofeijilu',
            name='ke_hu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kernel.operator', verbose_name='客户'),
        ),
        migrations.AddField(
            model_name='xiaofeijilu',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_pid', to='kernel.process', verbose_name='作业进程'),
        ),
        migrations.AddField(
            model_name='wuliaotaizhang',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_attributes', to='contenttypes.contenttype', verbose_name='隶属主体'),
        ),
        migrations.AddField(
            model_name='wuliaotaizhang',
            name='ling_yong_ren',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kernel.operator', verbose_name='领用人'),
        ),
        migrations.AddField(
            model_name='wuliaotaizhang',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_pid', to='kernel.process', verbose_name='作业进程'),
        ),
        migrations.AddField(
            model_name='wuliaotaizhang',
            name='ru_chu_ku_cao_zuo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='applications.ruchukucaozuo', verbose_name='入出库操作'),
        ),
        migrations.AddField(
            model_name='wuliaotaizhang',
            name='shi_yong_ren',
            field=models.ManyToManyField(blank=True, related_name='shi_yong_ren', to='kernel.operator', verbose_name='使用人'),
        ),
        migrations.AddField(
            model_name='suifangjilu',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_attributes', to='contenttypes.contenttype', verbose_name='隶属主体'),
        ),
        migrations.AddField(
            model_name='suifangjilu',
            name='ke_hu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kernel.operator', verbose_name='客户'),
        ),
        migrations.AddField(
            model_name='suifangjilu',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_pid', to='kernel.process', verbose_name='作业进程'),
        ),
        migrations.AddField(
            model_name='shuiguangzhenzhiliaojilu',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_attributes', to='contenttypes.contenttype', verbose_name='隶属主体'),
        ),
        migrations.AddField(
            model_name='shuiguangzhenzhiliaojilu',
            name='ke_hu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kernel.operator', verbose_name='客户'),
        ),
        migrations.AddField(
            model_name='shuiguangzhenzhiliaojilu',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_pid', to='kernel.process', verbose_name='作业进程'),
        ),
        migrations.AddField(
            model_name='ruchukucaozuo',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_attributes', to='contenttypes.contenttype', verbose_name='隶属主体'),
        ),
        migrations.AddField(
            model_name='ruchukucaozuo',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_pid', to='kernel.process', verbose_name='作业进程'),
        ),
        migrations.AddField(
            model_name='roudusuzhiliaojilu',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_attributes', to='contenttypes.contenttype', verbose_name='隶属主体'),
        ),
        migrations.AddField(
            model_name='roudusuzhiliaojilu',
            name='ke_hu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kernel.operator', verbose_name='客户'),
        ),
        migrations.AddField(
            model_name='roudusuzhiliaojilu',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_pid', to='kernel.process', verbose_name='作业进程'),
        ),
        migrations.AddField(
            model_name='qianshuzhiqingtongyishujilu',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_attributes', to='contenttypes.contenttype', verbose_name='隶属主体'),
        ),
        migrations.AddField(
            model_name='qianshuzhiqingtongyishujilu',
            name='fu_wu_xiang_mu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kernel.service', verbose_name='服务项目'),
        ),
        migrations.AddField(
            model_name='qianshuzhiqingtongyishujilu',
            name='ke_hu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kernel.operator', verbose_name='客户'),
        ),
        migrations.AddField(
            model_name='qianshuzhiqingtongyishujilu',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_pid', to='kernel.process', verbose_name='作业进程'),
        ),
        migrations.AddField(
            model_name='profile',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_attributes', to='contenttypes.contenttype', verbose_name='隶属主体'),
        ),
        migrations.AddField(
            model_name='profile',
            name='ke_hu_lai_yuan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='applications.kehulaiyuan', verbose_name='客户来源'),
        ),
        migrations.AddField(
            model_name='profile',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kernel.operator', verbose_name='人员'),
        ),
        migrations.AddField(
            model_name='profile',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_pid', to='kernel.process', verbose_name='作业进程'),
        ),
        migrations.AddField(
            model_name='material',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_attributes', to='contenttypes.contenttype', verbose_name='隶属主体'),
        ),
        migrations.AddField(
            model_name='material',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_pid', to='kernel.process', verbose_name='作业进程'),
        ),
        migrations.AddField(
            model_name='knowledge',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_attributes', to='contenttypes.contenttype', verbose_name='隶属主体'),
        ),
        migrations.AddField(
            model_name='knowledge',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_pid', to='kernel.process', verbose_name='作业进程'),
        ),
        migrations.AddField(
            model_name='kehulaiyuan',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_attributes', to='contenttypes.contenttype', verbose_name='隶属主体'),
        ),
        migrations.AddField(
            model_name='kehulaiyuan',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_pid', to='kernel.process', verbose_name='作业进程'),
        ),
        migrations.AddField(
            model_name='jiankangdiaochajilu',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_attributes', to='contenttypes.contenttype', verbose_name='隶属主体'),
        ),
        migrations.AddField(
            model_name='jiankangdiaochajilu',
            name='hun_fou',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='applications.hunfou', verbose_name='婚否'),
        ),
        migrations.AddField(
            model_name='jiankangdiaochajilu',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_pid', to='kernel.process', verbose_name='作业进程'),
        ),
        migrations.AddField(
            model_name='hunfou',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_attributes', to='contenttypes.contenttype', verbose_name='隶属主体'),
        ),
        migrations.AddField(
            model_name='hunfou',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_pid', to='kernel.process', verbose_name='作业进程'),
        ),
        migrations.AddField(
            model_name='huangjinweizhenzhiliaojilu',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_attributes', to='contenttypes.contenttype', verbose_name='隶属主体'),
        ),
        migrations.AddField(
            model_name='huangjinweizhenzhiliaojilu',
            name='ke_hu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kernel.operator', verbose_name='客户'),
        ),
        migrations.AddField(
            model_name='huangjinweizhenzhiliaojilu',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_pid', to='kernel.process', verbose_name='作业进程'),
        ),
        migrations.AddField(
            model_name='guosuanzhiliaojilu',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_attributes', to='contenttypes.contenttype', verbose_name='隶属主体'),
        ),
        migrations.AddField(
            model_name='guosuanzhiliaojilu',
            name='ke_hu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kernel.operator', verbose_name='客户'),
        ),
        migrations.AddField(
            model_name='guosuanzhiliaojilu',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_pid', to='kernel.process', verbose_name='作业进程'),
        ),
        migrations.AddField(
            model_name='guangzizhiliaojilu',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_attributes', to='contenttypes.contenttype', verbose_name='隶属主体'),
        ),
        migrations.AddField(
            model_name='guangzizhiliaojilu',
            name='ke_hu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kernel.operator', verbose_name='客户'),
        ),
        migrations.AddField(
            model_name='guangzizhiliaojilu',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_pid', to='kernel.process', verbose_name='作业进程'),
        ),
        migrations.AddField(
            model_name='fuwuleibie',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_attributes', to='contenttypes.contenttype', verbose_name='隶属主体'),
        ),
        migrations.AddField(
            model_name='fuwuleibie',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_pid', to='kernel.process', verbose_name='作业进程'),
        ),
        migrations.AddField(
            model_name='fasongzhiliaozhuyishixiangjilu',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_attributes', to='contenttypes.contenttype', verbose_name='隶属主体'),
        ),
        migrations.AddField(
            model_name='fasongzhiliaozhuyishixiangjilu',
            name='fu_wu_xiang_mu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kernel.service', verbose_name='服务项目'),
        ),
        migrations.AddField(
            model_name='fasongzhiliaozhuyishixiangjilu',
            name='ke_hu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kernel.operator', verbose_name='客户'),
        ),
        migrations.AddField(
            model_name='fasongzhiliaozhuyishixiangjilu',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_pid', to='kernel.process', verbose_name='作业进程'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_attributes', to='contenttypes.contenttype', verbose_name='隶属主体'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_pid', to='kernel.process', verbose_name='作业进程'),
        ),
        migrations.AddField(
            model_name='diaoqzhiliaojilu',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_attributes', to='contenttypes.contenttype', verbose_name='隶属主体'),
        ),
        migrations.AddField(
            model_name='diaoqzhiliaojilu',
            name='ke_hu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kernel.operator', verbose_name='客户'),
        ),
        migrations.AddField(
            model_name='diaoqzhiliaojilu',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_pid', to='kernel.process', verbose_name='作业进程'),
        ),
        migrations.AddField(
            model_name='device',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_attributes', to='contenttypes.contenttype', verbose_name='隶属主体'),
        ),
        migrations.AddField(
            model_name='device',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_pid', to='kernel.process', verbose_name='作业进程'),
        ),
        migrations.AddField(
            model_name='dengluqiandaojilu',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_attributes', to='contenttypes.contenttype', verbose_name='隶属主体'),
        ),
        migrations.AddField(
            model_name='dengluqiandaojilu',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_pid', to='kernel.process', verbose_name='作业进程'),
        ),
        migrations.AddField(
            model_name='chongzhijilu',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_attributes', to='contenttypes.contenttype', verbose_name='隶属主体'),
        ),
        migrations.AddField(
            model_name='chongzhijilu',
            name='ke_hu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kernel.operator', verbose_name='客户'),
        ),
        migrations.AddField(
            model_name='chongzhijilu',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_pid', to='kernel.process', verbose_name='作业进程'),
        ),
        migrations.AddField(
            model_name='chaoshengpaozhiliaojilu',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_attributes', to='contenttypes.contenttype', verbose_name='隶属主体'),
        ),
        migrations.AddField(
            model_name='chaoshengpaozhiliaojilu',
            name='ke_hu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kernel.operator', verbose_name='客户'),
        ),
        migrations.AddField(
            model_name='chaoshengpaozhiliaojilu',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_pid', to='kernel.process', verbose_name='作业进程'),
        ),
        migrations.AddField(
            model_name='capital',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_attributes', to='contenttypes.contenttype', verbose_name='隶属主体'),
        ),
        migrations.AddField(
            model_name='capital',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_pid', to='kernel.process', verbose_name='作业进程'),
        ),
    ]
