# Generated by Django 4.2.7 on 2024-11-27 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-id'], 'verbose_name': 'Dict-个人资料', 'verbose_name_plural': 'Dict-个人资料'},
        ),
    ]
