# Generated by Django 5.0.6 on 2024-05-13 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, null=True, verbose_name='标签')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='名称')),
                ('erpsys_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='ERPSysID')),
                ('pym', models.CharField(blank=True, max_length=255, null=True, verbose_name='拼音码')),
                ('field_type', models.CharField(blank=True, choices=[('CharField', '单行文本'), ('TextField', '多行文本'), ('IntegerField', '整数'), ('DecimalField', '固定精度小数'), ('DateTimeField', '日期时间'), ('DateField', '日期'), ('FileField', '文件'), ('Dictionary', '关联字段')], max_length=50, null=True, verbose_name='字段类型')),
                ('related_content', models.CharField(blank=True, max_length=100, null=True, verbose_name='关联内容')),
                ('choice_type', models.CharField(blank=True, choices=[('Select', '下拉单选'), ('RadioSelect', '单选按钮列表'), ('CheckboxSelectMultiple', '复选框列表'), ('SelectMultiple', '下拉多选')], max_length=50, null=True, verbose_name='类型')),
                ('max_length', models.PositiveSmallIntegerField(blank=True, default=100, null=True, verbose_name='最大长度')),
                ('max_digits', models.PositiveSmallIntegerField(blank=True, default=10, null=True, verbose_name='最大位数')),
                ('decimal_places', models.PositiveSmallIntegerField(blank=True, default=2, null=True, verbose_name='小数位数')),
            ],
            options={
                'verbose_name': '表单字段',
                'verbose_name_plural': '表单字段',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('form_type', models.CharField(choices=[('RESOURCE_ATTRIBUTES', '资源属性'), ('PRODUCE', '服务产出'), ('WORK_ORDER', '服务工单'), ('KNOWLEDGE', '知识')], max_length=50, verbose_name='类型')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '表单',
                'verbose_name_plural': '表单',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FormComponents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=10, verbose_name='顺序')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='design.field', verbose_name='字段')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='design.form', verbose_name='表单')),
            ],
            options={
                'verbose_name': '表单字段',
                'verbose_name_plural': '表单字段',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='form',
            name='fields',
            field=models.ManyToManyField(through='design.FormComponents', to='design.field', verbose_name='字段'),
        ),
    ]
