# Generated by Django 4.2.7 on 2024-05-21 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, null=True, verbose_name='标签')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='名称')),
                ('pym', models.CharField(blank=True, max_length=255, null=True, verbose_name='拼音码')),
                ('erpsys_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='ERPSysID')),
                ('bind_system_object', models.CharField(blank=True, choices=[('User', '系统用户'), ('DateTime', '系统时间'), ('Date', '系统日期'), ('Timer', '系统计时器'), ('ResourceLaborHours', '人工工时资源'), ('ResourceEquipmentHours', '员工工时资源'), ('ResourceMaterial', '物料资源'), ('ResourceCapital', '资金资源'), ('ResourceKnowledge', '知识资源'), ('CreateService', '创建服务'), ('CallService', '调用服务')], max_length=50, null=True, verbose_name='绑定系统对象')),
                ('content', models.JSONField(blank=True, null=True, verbose_name='内容')),
            ],
            options={
                'verbose_name': '字典',
                'verbose_name_plural': '字典',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, null=True, verbose_name='标签')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='名称')),
                ('pym', models.CharField(blank=True, max_length=255, null=True, verbose_name='拼音码')),
                ('erpsys_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='ERPSysID')),
                ('field_type', models.CharField(blank=True, choices=[('CharField', '单行文本'), ('IntegerField', '整数'), ('DecimalField', '固定精度小数'), ('DictionaryField', '字典字段'), ('TextField', '多行文本'), ('DateTimeField', '日期时间'), ('DateField', '日期'), ('FileField', '文件'), ('ComputedField', '计算字段')], default='CharField', max_length=50, null=True, verbose_name='字段类型')),
                ('is_entity', models.BooleanField(default=False, verbose_name='业务实体')),
                ('choice_type', models.CharField(blank=True, choices=[('Select', '下拉单选'), ('RadioSelect', '单选按钮列表'), ('CheckboxSelectMultiple', '复选框列表'), ('SelectMultiple', '下拉多选')], max_length=50, null=True, verbose_name='选择类型')),
                ('max_length', models.PositiveSmallIntegerField(blank=True, default=100, null=True, verbose_name='最大长度')),
                ('max_digits', models.PositiveSmallIntegerField(blank=True, default=10, null=True, verbose_name='最大位数')),
                ('decimal_places', models.PositiveSmallIntegerField(blank=True, default=2, null=True, verbose_name='小数位数')),
                ('api_field_type', models.CharField(blank=True, choices=[('hssc_group_no', '组别'), ('hssc_charge_staff', '责任人'), ('hssc_operator', '作业人员'), ('hssc_scheduled_time', '计划执行时间'), ('hssc_duration', '天数'), ('hssc_frequency', '频次'), ('hssc_name', '姓名'), ('hssc_customer_number', '居民档案号'), ('hssc_phone_no', '联系电话'), ('hssc_address', '家庭地址')], max_length=50, null=True, verbose_name='API字段类型')),
                ('api_field_default_value', models.CharField(blank=True, choices=[('CurrentOperator', '当前用户'), ('SystemTime', '当前时间')], max_length=50, null=True, verbose_name='API字段默认值')),
                ('computed_logic', models.TextField(blank=True, null=True, verbose_name='计算逻辑')),
                ('related_dictionary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='design.dictionary', verbose_name='关联字典')),
            ],
            options={
                'verbose_name': '字段',
                'verbose_name_plural': '字段',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, null=True, verbose_name='标签')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='名称')),
                ('pym', models.CharField(blank=True, max_length=255, null=True, verbose_name='拼音码')),
                ('erpsys_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='ERPSysID')),
                ('form_type', models.CharField(choices=[('PRODUCE', '服务作业'), ('WORK_ORDER', '服务工单'), ('DICT', '字典'), ('ENTITY', '实体'), ('Document', '文档')], max_length=50, verbose_name='类型')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '表单',
                'verbose_name_plural': '表单',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, null=True, verbose_name='标签')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='名称')),
                ('pym', models.CharField(blank=True, max_length=255, null=True, verbose_name='拼音码')),
                ('erpsys_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='ERPSysID')),
                ('domain', models.CharField(blank=True, max_length=255, null=True, verbose_name='域名')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='项目描述')),
            ],
            options={
                'verbose_name': '项目列表',
                'verbose_name_plural': '项目列表',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ResourceObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, null=True, verbose_name='标签')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='名称')),
                ('pym', models.CharField(blank=True, max_length=255, null=True, verbose_name='拼音码')),
                ('erpsys_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='ERPSysID')),
                ('resource_type', models.CharField(choices=[('Material', '物料'), ('EquipmentWorkingTime', '设备工时'), ('OperatorWorkingTime', '人工工时'), ('Money', '资金'), ('KNOWLEDGE', '知识')], max_length=50, verbose_name='类型')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='描述')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='关联内容')),
            ],
            options={
                'verbose_name': '资源对象',
                'verbose_name_plural': '资源对象',
                'ordering': ['resource_type', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceBOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, null=True, verbose_name='标签')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='名称')),
                ('pym', models.CharField(blank=True, max_length=255, null=True, verbose_name='拼音码')),
                ('erpsys_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='ERPSysID')),
                ('service_type', models.CharField(choices=[('OPERATION', '作业'), ('SERVICE', '服务')], max_length=50, verbose_name='服务类型')),
                ('api_fields', models.JSONField(blank=True, null=True, verbose_name='API字段')),
                ('unit', models.CharField(blank=True, max_length=50, null=True, verbose_name='单位')),
                ('estimated_time', models.IntegerField(blank=True, null=True, verbose_name='预计工时')),
                ('estimated_cost', models.IntegerField(blank=True, null=True, verbose_name='预计成本')),
                ('program', models.JSONField(blank=True, null=True, verbose_name='服务程序')),
                ('produce', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produce_bom', to='design.form', verbose_name='服务产出')),
                ('resource_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='design.resourceobject', verbose_name='资源对象')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_order_bom', to='design.form', verbose_name='服务工单')),
            ],
            options={
                'verbose_name': '服务BOM',
                'verbose_name_plural': '服务BOM',
                'ordering': ['service_type', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SystemCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, null=True, verbose_name='标签')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='名称')),
                ('pym', models.CharField(blank=True, max_length=255, null=True, verbose_name='拼音码')),
                ('erpsys_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='ERPSysID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SystemObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, null=True, verbose_name='标签')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='名称')),
                ('pym', models.CharField(blank=True, max_length=255, null=True, verbose_name='拼音码')),
                ('erpsys_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='ERPSysID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, null=True, verbose_name='标签')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='名称')),
                ('pym', models.CharField(blank=True, max_length=255, null=True, verbose_name='拼音码')),
                ('erpsys_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='ERPSysID')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, limit_choices_to=models.Q(('app_label', 'design'), models.Q(('model', 'field'), ('model', 'dictionary'), _connector='OR')), null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': '业务词汇',
                'verbose_name_plural': '业务词汇',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SourceCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(null=True, verbose_name='源代码')),
                ('description', models.TextField(blank=True, max_length=255, null=True, verbose_name='描述')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='design.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '作业系统脚本',
                'verbose_name_plural': '作业系统脚本',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='services',
            field=models.ManyToManyField(blank=True, to='design.servicebom', verbose_name='服务'),
        ),
        migrations.CreateModel(
            name='FormListComponents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_value', models.CharField(blank=True, max_length=255, null=True, verbose_name='默认值')),
                ('inherit_value', models.BooleanField(default=True, verbose_name='继承值')),
                ('is_required', models.BooleanField(default=False, verbose_name='是否必填')),
                ('order', models.PositiveSmallIntegerField(default=100, verbose_name='顺序')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='design.field', verbose_name='字段')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='design.form', verbose_name='表单')),
            ],
            options={
                'verbose_name': '表单列表字段',
                'verbose_name_plural': '表单列表字段',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FormComponents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_value', models.CharField(blank=True, max_length=255, null=True, verbose_name='默认值')),
                ('inherit_value', models.BooleanField(default=True, verbose_name='继承值')),
                ('is_required', models.BooleanField(default=False, verbose_name='是否必填')),
                ('order', models.PositiveSmallIntegerField(default=10, verbose_name='顺序')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='design.field', verbose_name='字段')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='design.form', verbose_name='表单')),
            ],
            options={
                'verbose_name': '表单字段',
                'verbose_name_plural': '表单字段',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='form',
            name='fields',
            field=models.ManyToManyField(through='design.FormComponents', to='design.field', verbose_name='字段'),
        ),
        migrations.CreateModel(
            name='DictionaryFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_multivalued', models.BooleanField(default=False, verbose_name='多值')),
                ('default_value_char', models.CharField(blank=True, max_length=255, null=True, verbose_name='默认值')),
                ('order', models.PositiveSmallIntegerField(default=10, verbose_name='顺序')),
                ('dictionary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='design.dictionary', verbose_name='字典')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='design.field', verbose_name='字段')),
            ],
            options={
                'verbose_name': '字典字段',
                'verbose_name_plural': '字典字段',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='dictionary',
            name='fields',
            field=models.ManyToManyField(through='design.DictionaryFields', to='design.field', verbose_name='字段'),
        ),
        migrations.CreateModel(
            name='ServiceBOMDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='design.servicebom', verbose_name='子组件')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='design.servicebom', verbose_name='父组件')),
            ],
            options={
                'verbose_name': '组件依赖',
                'verbose_name_plural': '组件依赖',
                'ordering': ['id'],
                'unique_together': {('parent', 'child')},
            },
        ),
    ]
