# Generated by Django 4.2.7 on 2024-07-10 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capitalrequirements',
            options={'ordering': ['id'], 'verbose_name': '资金资源', 'verbose_name_plural': '资金资源'},
        ),
        migrations.AlterModelOptions(
            name='devicerequirements',
            options={'ordering': ['id'], 'verbose_name': '器材资源', 'verbose_name_plural': '器材资源'},
        ),
        migrations.AlterModelOptions(
            name='equipmentrequirements',
            options={'ordering': ['id'], 'verbose_name': '设备资源', 'verbose_name_plural': '设备资源'},
        ),
        migrations.AlterModelOptions(
            name='knowledgerequirements',
            options={'ordering': ['id'], 'verbose_name': '知识资源', 'verbose_name_plural': '知识资源'},
        ),
        migrations.AlterModelOptions(
            name='materialrequirements',
            options={'ordering': ['id'], 'verbose_name': '物料资源', 'verbose_name_plural': '物料资源'},
        ),
    ]
