# Generated by Django 5.0.6 on 2024-05-13 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formcomponents',
            name='default_value',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='默认值'),
        ),
        migrations.AddField(
            model_name='formcomponents',
            name='inherit_value',
            field=models.BooleanField(default=True, verbose_name='继承值'),
        ),
        migrations.AddField(
            model_name='formcomponents',
            name='is_required',
            field=models.BooleanField(default=False, verbose_name='是否必填'),
        ),
        migrations.AlterField(
            model_name='field',
            name='choice_type',
            field=models.CharField(blank=True, choices=[('Select', '下拉单选'), ('RadioSelect', '单选按钮列表'), ('CheckboxSelectMultiple', '复选框列表'), ('SelectMultiple', '下拉多选')], max_length=50, null=True, verbose_name='选择类型'),
        ),
        migrations.AlterField(
            model_name='field',
            name='field_type',
            field=models.CharField(blank=True, choices=[('CharField', '单行文本'), ('TextField', '多行文本'), ('IntegerField', '整数'), ('DecimalField', '固定精度小数'), ('DateTimeField', '日期时间'), ('DateField', '日期'), ('FileField', '文件'), ('Dictionary', '关联字段')], default='CharField', max_length=50, null=True, verbose_name='字段类型'),
        ),
        migrations.CreateModel(
            name='FormListComponents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inherit_value', models.BooleanField(default=True, verbose_name='继承值')),
                ('default_value', models.CharField(blank=True, max_length=255, null=True, verbose_name='默认值')),
                ('is_required', models.BooleanField(default=False, verbose_name='是否必填')),
                ('order', models.PositiveSmallIntegerField(default=100, verbose_name='顺序')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='design.field', verbose_name='字段')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='design.form', verbose_name='表单')),
            ],
            options={
                'verbose_name': '表单列表字段设置',
                'verbose_name_plural': '表单列表字段设置',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SystemAPIField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, null=True, verbose_name='标签')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='名称')),
                ('erpsys_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='ERPSysID')),
                ('pym', models.CharField(blank=True, max_length=255, null=True, verbose_name='拼音码')),
                ('type', models.CharField(choices=[('hssc_group_no', '组别'), ('hssc_charge_staff', '责任人'), ('hssc_operator', '作业人员'), ('hssc_scheduled_time', '计划执行时间'), ('hssc_duration', '天数'), ('hssc_frequency', '频次'), ('hssc_name', '姓名'), ('hssc_customer_number', '居民档案号'), ('hssc_phone_no', '联系电话'), ('hssc_address', '家庭地址')], max_length=50, verbose_name='系统API字段')),
                ('default_value', models.CharField(blank=True, choices=[('CurrentOperator', '当前用户'), ('SystemTime', '当前时间')], max_length=50, null=True, verbose_name='默认值')),
                ('component', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='design.field', verbose_name='业务字段')),
            ],
            options={
                'verbose_name': '系统API字段',
                'verbose_name_plural': '系统API字段',
            },
        ),
    ]
