# Generated by Django 5.0.6 on 2024-05-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0002_formcomponents_default_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='erpsys_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='ERPSysID'),
        ),
        migrations.AddField(
            model_name='form',
            name='label',
            field=models.CharField(max_length=255, null=True, verbose_name='标签'),
        ),
        migrations.AddField(
            model_name='form',
            name='pym',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='拼音码'),
        ),
        migrations.AlterField(
            model_name='form',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='名称'),
        ),
    ]
