# Generated by Django 5.0.6 on 2024-05-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0003_form_erpsys_id_form_label_form_pym_alter_form_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='related_field_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='关联字段名称'),
        ),
        migrations.AlterField(
            model_name='form',
            name='form_type',
            field=models.CharField(choices=[('PRODUCE', '服务作业'), ('WORK_ORDER', '服务工单'), ('ENTITY_ATTRIBUTES', '实体属性'), ('KNOWLEDGE', '知识')], max_length=50, verbose_name='类型'),
        ),
    ]
