# Generated by Django 5.0.6 on 2024-05-13 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0004_field_related_field_name_alter_form_form_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='api_field_default_value',
            field=models.CharField(blank=True, choices=[('CurrentOperator', '当前用户'), ('SystemTime', '当前时间')], max_length=50, null=True, verbose_name='API字段默认值'),
        ),
        migrations.AddField(
            model_name='field',
            name='api_field_type',
            field=models.CharField(blank=True, choices=[('hssc_group_no', '组别'), ('hssc_charge_staff', '责任人'), ('hssc_operator', '作业人员'), ('hssc_scheduled_time', '计划执行时间'), ('hssc_duration', '天数'), ('hssc_frequency', '频次'), ('hssc_name', '姓名'), ('hssc_customer_number', '居民档案号'), ('hssc_phone_no', '联系电话'), ('hssc_address', '家庭地址')], max_length=50, null=True, verbose_name='API字段类型'),
        ),
        migrations.DeleteModel(
            name='SystemAPIField',
        ),
    ]
