# Generated by Django 5.0.6 on 2024-05-13 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0005_field_api_field_default_value_field_api_field_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, null=True, verbose_name='标签')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='名称')),
                ('pym', models.CharField(blank=True, max_length=255, null=True, verbose_name='拼音码')),
                ('erpsys_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='ERPSysID')),
                ('domain', models.CharField(blank=True, max_length=255, null=True, verbose_name='域名')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='项目描述')),
            ],
            options={
                'verbose_name': '项目列表',
                'verbose_name_plural': '项目列表',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, null=True, verbose_name='标签')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='名称')),
                ('pym', models.CharField(blank=True, max_length=255, null=True, verbose_name='拼音码')),
                ('erpsys_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='ERPSysID')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='岗位描述')),
            ],
            options={
                'verbose_name': '业务岗位',
                'verbose_name_plural': '业务岗位',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='formlistcomponents',
            options={'ordering': ['order'], 'verbose_name': '表单列表字段', 'verbose_name_plural': '表单列表字段'},
        ),
        migrations.AddField(
            model_name='field',
            name='computed_logic',
            field=models.TextField(blank=True, null=True, verbose_name='计算逻辑'),
        ),
        migrations.AlterField(
            model_name='field',
            name='field_type',
            field=models.CharField(blank=True, choices=[('CharField', '单行文本'), ('TextField', '多行文本'), ('IntegerField', '整数'), ('DecimalField', '固定精度小数'), ('DateTimeField', '日期时间'), ('DateField', '日期'), ('FileField', '文件'), ('RelationField', '关联字段'), ('ComputedField', '计算字段')], default='CharField', max_length=50, null=True, verbose_name='字段类型'),
        ),
        migrations.AlterField(
            model_name='form',
            name='form_type',
            field=models.CharField(choices=[('PRODUCE', '服务作业'), ('WORK_ORDER', '服务工单'), ('DICT', '字典'), ('ENTITY', '实体'), ('KNOWLEDGE', '知识')], max_length=50, verbose_name='类型'),
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, null=True, verbose_name='标签')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='名称')),
                ('pym', models.CharField(blank=True, max_length=255, null=True, verbose_name='拼音码')),
                ('erpsys_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='ERPSysID')),
                ('base_form', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='design.form', verbose_name='基础表单')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='design.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '管理实体',
                'verbose_name_plural': '管理实体',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='roles',
            field=models.ManyToManyField(blank=True, to='design.role', verbose_name='角色'),
        ),
        migrations.CreateModel(
            name='SourceCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(null=True, verbose_name='源代码')),
                ('description', models.TextField(blank=True, max_length=255, null=True, verbose_name='描述')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='design.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '作业系统脚本',
                'verbose_name_plural': '作业系统脚本',
                'ordering': ['id'],
            },
        ),
    ]
