# Generated by Django 4.2.7 on 2024-07-04 03:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FuWuLeiBie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, null=True, verbose_name='中文名称')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='名称')),
                ('pym', models.CharField(blank=True, max_length=255, null=True, verbose_name='拼音码')),
                ('maor_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='ERPSysID')),
            ],
            options={
                'verbose_name': 'Dict-服务类别',
                'verbose_name_plural': 'Dict-服务类别',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='GangWei',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, null=True, verbose_name='中文名称')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='名称')),
                ('pym', models.CharField(blank=True, max_length=255, null=True, verbose_name='拼音码')),
                ('maor_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='ERPSysID')),
            ],
            options={
                'verbose_name': 'Dict-岗位',
                'verbose_name_plural': 'Dict-岗位',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='GongJu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, null=True, verbose_name='中文名称')),
                ('pym', models.CharField(blank=True, max_length=255, null=True, verbose_name='拼音码')),
                ('maor_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='ERPSysID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='名称')),
            ],
            options={
                'verbose_name': '工具',
                'verbose_name_plural': '工具',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='KongJian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, null=True, verbose_name='中文名称')),
                ('pym', models.CharField(blank=True, max_length=255, null=True, verbose_name='拼音码')),
                ('maor_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='ERPSysID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='名称')),
            ],
            options={
                'verbose_name': '空间',
                'verbose_name_plural': '空间',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RenYuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, null=True, verbose_name='中文名称')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='名称')),
                ('pym', models.CharField(blank=True, max_length=255, null=True, verbose_name='拼音码')),
                ('maor_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='ERPSysID')),
                ('xing_ming', models.CharField(blank=True, max_length=100, null=True, verbose_name='姓名')),
                ('gang_wei', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maor.gangwei', verbose_name='岗位')),
                ('xi_tong_yong_hu', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='系统用户')),
            ],
            options={
                'verbose_name': '人员',
                'verbose_name_plural': '人员',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RuChuKuCaoZuo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, null=True, verbose_name='中文名称')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='名称')),
                ('pym', models.CharField(blank=True, max_length=255, null=True, verbose_name='拼音码')),
                ('maor_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='ERPSysID')),
            ],
            options={
                'verbose_name': 'Dict-入出库操作',
                'verbose_name_plural': 'Dict-入出库操作',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SheBei',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, null=True, verbose_name='中文名称')),
                ('pym', models.CharField(blank=True, max_length=255, null=True, verbose_name='拼音码')),
                ('maor_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='ERPSysID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='名称')),
            ],
            options={
                'verbose_name': '设备',
                'verbose_name_plural': '设备',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='WuLiao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, null=True, verbose_name='中文名称')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='名称')),
                ('pym', models.CharField(blank=True, max_length=255, null=True, verbose_name='拼音码')),
                ('maor_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='ERPSysID')),
            ],
            options={
                'verbose_name': '物料',
                'verbose_name_plural': '物料',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='XinXi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, null=True, verbose_name='中文名称')),
                ('pym', models.CharField(blank=True, max_length=255, null=True, verbose_name='拼音码')),
                ('maor_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='ERPSysID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='名称')),
            ],
            options={
                'verbose_name': '信息',
                'verbose_name_plural': '信息',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ZiJin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, null=True, verbose_name='中文名称')),
                ('pym', models.CharField(blank=True, max_length=255, null=True, verbose_name='拼音码')),
                ('maor_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='ERPSysID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='名称')),
            ],
            options={
                'verbose_name': '资金',
                'verbose_name_plural': '资金',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='WuLiaoTaiZhang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, null=True, verbose_name='中文名称')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='名称')),
                ('pym', models.CharField(blank=True, max_length=255, null=True, verbose_name='拼音码')),
                ('maor_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='ERPSysID')),
                ('shu_liang', models.IntegerField(blank=True, null=True, verbose_name='数量')),
                ('ri_qi', models.DateTimeField(blank=True, null=True, verbose_name='入出库时间')),
                ('you_xiao_qi', models.DateField(blank=True, null=True, verbose_name='有效期')),
                ('ling_yong_ren', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ling_yong_ren', to='maor.renyuan', verbose_name='领用人')),
                ('ru_chu_ku_cao_zuo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maor.ruchukucaozuo', verbose_name='入出库操作')),
                ('shi_yong_ren', models.ManyToManyField(blank=True, related_name='shi_yong_ren', to='maor.renyuan', verbose_name='使用人')),
                ('wu_liao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maor.wuliao', verbose_name='物料')),
            ],
            options={
                'verbose_name': '物料台账',
                'verbose_name_plural': '物料台账',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FuWu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, null=True, verbose_name='中文名称')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='名称')),
                ('pym', models.CharField(blank=True, max_length=255, null=True, verbose_name='拼音码')),
                ('maor_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='ERPSysID')),
                ('gong_dan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gong_dan', to='maor.xinxi', verbose_name='工单')),
            ],
            options={
                'verbose_name': '服务',
                'verbose_name_plural': '服务',
                'ordering': ['id'],
            },
        ),
    ]
