# Generated by Django 4.2.7 on 2024-06-13 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('design', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='进程id')),
                ('state', models.CharField(choices=[('NEW', '新建'), ('READY', '就绪'), ('EXECUTING', '执行中'), ('WAITING', '等待'), ('TERMINATED', '终止')], default='NEW', max_length=50, verbose_name='状态')),
                ('program', models.JSONField(blank=True, null=True, verbose_name='程序')),
                ('pc', models.PositiveIntegerField(blank=True, null=True, verbose_name='程序计数器')),
                ('registers', models.JSONField(blank=True, null=True, verbose_name='寄存器')),
                ('io_status', models.JSONField(blank=True, null=True, verbose_name='I/O状态')),
                ('cpu_scheduling', models.JSONField(blank=True, null=True, verbose_name='CPU调度')),
                ('accounting', models.JSONField(blank=True, null=True, verbose_name='帐务')),
                ('sp', models.PositiveIntegerField(blank=True, null=True, verbose_name='栈指针')),
                ('pcb', models.JSONField(blank=True, null=True, verbose_name='进程控制块')),
                ('stack', models.JSONField(blank=True, null=True, verbose_name='栈')),
                ('heap', models.JSONField(blank=True, null=True, verbose_name='堆')),
                ('schedule_context', models.JSONField(blank=True, null=True, verbose_name='调度上下文')),
                ('control_context', models.JSONField(blank=True, null=True, verbose_name='控制上下文')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('updated_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_instances', to='kernel.process', verbose_name='父进程')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='design.service', verbose_name='服务')),
            ],
            options={
                'verbose_name': '进程',
                'verbose_name_plural': '进程',
                'ordering': ['id'],
            },
        ),
    ]
