# Generated by Django 4.2.7 on 2024-12-03 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessFrameState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, null=True, verbose_name='中文名称')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='名称')),
                ('pym', models.CharField(blank=True, max_length=255, null=True, verbose_name='拼音码')),
                ('erpsys_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='ERPSysID')),
                ('status', models.CharField(max_length=50, verbose_name='状态')),
                ('local_vars', models.JSONField(blank=True, null=True, verbose_name='本地变量')),
                ('inherited_context', models.JSONField(blank=True, null=True, verbose_name='继承上下文')),
                ('return_value', models.JSONField(blank=True, null=True, verbose_name='返回值')),
                ('timestamp', models.DateTimeField(auto_now=True, verbose_name='时间戳')),
                ('parent_frame', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kernel.processframestate', verbose_name='父栈帧')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kernel.process', verbose_name='进程')),
            ],
            options={
                'verbose_name': '进程栈帧状态',
                'verbose_name_plural': '进程栈帧状态',
                'ordering': ['-timestamp'],
            },
        ),
    ]
